### ISSUE TITLE
Target weight wrongly says it has already been achieved, while it is not

### ISSUE THREAD

**Issue by fincentxyz** [QuantumPhysique/trale#166] opened 2024-11-21 11:23 UTC
**Describe the bug**
I recently updated from 0.7.2 to 0.8.1 and this update broke the target weight status.

**To Reproduce**
1. Download trale version 0.8.1 from F-Droid
2. Set your target weight above your current weight (e.g. target=80, current=70)
3. A celebration emoji is shown in the home page and achievements page

**Expected behavior**
I expect to see the amount of days estimated to reach my goal (which was shown previously)

**User Information**
 - Device: Pixel 8
 - OS: GrapheneOS Android 15
 - Version: 0.8.1
 - Downloaded: F-Droid

**Comment by gwosd** [comment] 2024-11-21 11:38
Thanks for using the app :)

If I understand you correctly, you are interesseted in gaining weight. 
At the moment only losing weight is implemented. 
However, we are planning to implement this feature #142.

**Comment by fincentxyz** [comment] 2024-11-21 11:42
Ah I see, that explains! Strange that the target weight for weight gain did work in 0.7.2

**Comment by braniii** [comment] 2024-11-22 17:55
@fincentxyz Just out of interest: Did trale show you a negative time at which you will reach your target weight? Well, I thought I caught that before the first public release, but apparently that didn't work. So unfortunately I have to tell you that the function was a (welcome) bug :sweat_smile: Anyway, the plan is to implement this soon

**Comment by braniii** [comment] 2024-11-22 17:56
Thx for your feedback. I'll close this, as it is a duplicate of #142.

**Closed by braniii** 2024-11-22 17:56 UTC
Labels: bug

**Comment by braniii** [comment] 2025-02-15 17:52
In the latest version v0.9.2, the mode is implemented experimentally. You can activate the mode in the settings at the bottom. I would appreciate your feedback so that we can improve it for the next release.

**Comment by fincentxyz** [comment] 2025-02-16 15:54
Hi, thanks for implementing this new mode! It looks like everything is working fine. I am only confused about the 'total change' tile in the achievements tab. How is that calculated?
