### ISSUE TITLE
Total change achievement reports wrong/unexpected number

### ISSUE THREAD

**Issue by fincentxyz** [QuantumPhysique/trale#167] opened 2024-11-21 11:26 UTC
**Describe the bug**
The newly introduced achievement page shows wrong information for the 'total change' achievement.

**To Reproduce**
Steps to reproduce the achievements issue:
1. Add for example three measurements (e.g. 67, 68 and 69)
2. Go to the achievements page
3. Reported 'total change' is 0.0

(With my personal tracking data, I gained 1.2kg when I compare the first measurement to the last measurement But, it is reporting a total change of 0.5kg.)

**Expected behavior**
I expect to see 1.2kg in my personal case or another measurement that makes more sense. Or maybe an explanation when I tap on the achievement on how that measurement is calculated.

**User Information**
 - Device: Pixel 8
 - OS: GrapheneOS Android 15
 - Version: 0.8.1
 - Downloaded: F-Droid

**Comment by fincentxyz** [comment] 2024-11-21 11:44
I understand where the number is coming from now. It is the difference between the highest and current measurement. As this app is currently designed for weight loss, this achievement displays an unexpected number when using it for weight gain.

**Comment by gwosd** [comment] 2024-11-21 11:47
Excatly :)

**Comment by braniii** [comment] 2024-11-22 17:56
Thx for your feedback. I'll close this, as it is a duplicate of #142.

**Closed** 2024-11-23 15:31 UTC
Labels: bug
